import pygame

def getkey(key):
    match key:
        case pygame.K_0:
            return '0'
        case pygame.K_1:
            return '1'
        case pygame.K_2:
            return '2'
        case pygame.K_3:
            return '3'
        case pygame.K_4:
            return '4'
        case pygame.K_5:
            return '5'
        case pygame.K_6:
            return '6'
        case pygame.K_7:
            return '7'
        case pygame.K_8:
            return '8'
        case pygame.K_9:
            return '9'
        case pygame.K_a:
            return 'a'
        case pygame.K_b:
            return 'b'
        case pygame.K_c:
            return 'c'
        case pygame.K_d:
            return 'd'
        case pygame.K_e:
            return 'e'
        case pygame.K_f:
            return 'f'
        case pygame.K_g:
            return 'g'
        case pygame.K_h:
            return 'h'
        case pygame.K_i:
            return 'i'
        case pygame.K_j:
            return 'j'
        case pygame.K_k:
            return 'k'
        case pygame.K_l:
            return 'l'
        case pygame.K_m:
            return 'm'
        case pygame.K_n:
            return 'n'
        case pygame.K_o:
            return 'o'
        case pygame.K_p:
            return 'p'
        case pygame.K_q:
            return 'q'
        case pygame.K_r:
            return 'r'
        case pygame.K_s:
            return 's'
        case pygame.K_t:
            return 't'
        case pygame.K_u:
            return 'u'
        case pygame.K_v:
            return 'v'
        case pygame.K_w:
            return 'w'
        case pygame.K_x:
            return 'x'
        case pygame.K_y:
            return 'y'
        case pygame.K_z:
            return 'z'
        case pygame.K_RETURN:
            return 'return'
        case _:
            '*'